apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: s3-fuse-flex-volume-deployer
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: s3-fuse-flex-volume-deployer
  template:
    metadata:
      name: s3-fuse-flex-volume-deployer
      labels:
        app: s3-fuse-flex-volume-deployer
      annotations:
        checksum/config-map: {{ include (print .Template.BasePath "/fuse_install_deps.yaml") . | sha256sum }}
    spec:
      initContainers:
        - name: install-host-deps
          image: busybox:latest
          imagePullPolicy: Always
          securityContext:
              privileged: true
          volumeMounts:
            - mountPath: /rootfs
              name: rootfs
            - mountPath: /script
              name: install-host-deps-script
          command:
            - sh
            - -c
            - cp /script/install_deps.sh /rootfs/tmp/ && chroot /rootfs sh /tmp/install_deps.sh
        - name: s3-flex-volume-drivers-deploy
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          securityContext:
              privileged: true
          volumeMounts:
            - mountPath: /flexmnt
              name: flexvolume-plugindir
            - mountPath: /hostbin
              name: flexvolume-usrlocalbin
      containers:
        - name: pause
          image: gcr.io/google-containers/pause
      volumes:
        - name: flexvolume-plugindir
          hostPath:
            path: {{ .Values.flexVolume.pluginDir | quote }}
        - name: flexvolume-usrlocalbin
          hostPath:
            path: '/usr/local/bin'
        - name: rootfs
          hostPath:
            path: /
            type: Directory
        - name: install-host-deps-script
          configMap:
            name: fuse-install-deps-script
      tolerations:
        - key: dedicated
          operator: Exists
